name: Build and Push Docker Image

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: compliance-system

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug GitHub Context
        run: |
          echo "Repository : ${{ github.repository }}"
          echo "Branch     : ${{ github.ref }}"
          echo "Actor      : ${{ github.actor }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::324621154851:role/GitHubActionsComplianceRole
          role-session-name: GitHubActionsSession
          aws-region: ap-south-1
          mask-aws-account-id: false

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.run_number }} \
            -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest \
            .

      - name: Run Trivy Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.run_number }}
          format: table
          exit-code: 0
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Push Docker Images
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.run_number }}
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest

      - name: Generate Build Metadata
        run: |
          mkdir -p artifacts

          cat <<EOF > artifacts/build-metadata.json
          {
            "repository":"${{ github.repository }}",
            "branch":"${{ github.ref_name }}",
            "commit":"${{ github.sha }}",
            "actor":"${{ github.actor }}",
            "workflow":"${{ github.workflow }}",
            "run_number":"${{ github.run_number }}",
            "image":"${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}",
            "tag":"${{ github.run_number }}",
            "timestamp":"$(date -u +%Y-%m-%dT%H:%M:%SZ)"
          }
          EOF

      - name: Upload Build Metadata
        uses: actions/upload-artifact@v4
        with:
          name: build-metadata
          path: artifacts/build-metadata.json
